name: "CI - Test Templates"
on:
  push:
    branches: [main]
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            elixir-asdf: ./**/elixir-asdf/**
            elixir-asdf-postgres: ./**/elixir-asdf-postgres/**

  test:
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.templates != '[]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
    steps:
      - uses: actions/checkout@v4

      - name: Smoke test for '${{ matrix.templates }}'
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.templates }}"
